### ISSUE TITLE
python3.6 error

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#100]
pi@raspberrypi:~/JoustMania $ sudo ./joust.sh 
Traceback (most recent call last):
  File "/home/pi/JoustMania/piparty.py", line 2, in <module>
    import common, joust
  File "/home/pi/JoustMania/joust.py", line 8, in <module>
    from piaudio import Audio
  File "/home/pi/JoustMania/piaudio.py", line 9, in <module>
    import pygame
  File "/usr/lib/python3/dist-packages/pygame/__init__.py", line 133, in <module>
    from pygame.base import *
ModuleNotFoundError: No module named 'pygame.base'

**Comment by adangert** [comment]
code is localized to the python3.6 branch

**Comment by adangert** [comment]
I should be able to test the python3.6 branch sometime soon and see if it works

**Comment by adangert** [comment]
current errors on the python3.6 branch:

pi@raspberrypi:~/JoustMania $ sudo ./joust.sh 
./joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory
pi@raspberrypi:~/JoustMania $ ./joust.sh 
Not root. Using sudo.
./joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory
pi@raspberrypi:~/JoustMania $ 


also:
pi@raspberrypi:~/JoustMania $ sudo cat /var/log/supervisor/joustmania-stderr---supervisor-bf9DQh.log 
/home/pi/JoustMania/joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory
/home/pi/JoustMania/joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory
/home/pi/JoustMania/joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory
/home/pi/JoustMania/joust.sh: line 10: /home/pi/JoustMania/venv/bin/python3.6: No such file or directory

**Comment by adangert** [comment]
all bugs have been worked out
