### ISSUE TITLE
pygame.mixer not working

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#258]
Here is the error:
pygame 2.0.0 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
linux
/home/pi/JoustMania/piaudio.py:272: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
(ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
  pygame.mixer.init(47000, -16, 2 , 4096)
Traceback (most recent call last):
  File "/home/pi/JoustMania/piparty.py", line 1047, in <module>
    InitAudio()
  File "/home/pi/JoustMania/piaudio.py", line 272, in InitAudio
    pygame.mixer.init(47000, -16, 2 , 4096)
  File "/home/pi/JoustMania/venv/lib/python3.7/site-packages/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)

**Comment by adangert** [comment]
included libsdl2-mixer-2.0-0 in the setup.py script, this will ask to do an update for joustmania devices, but should enable them to work from installing from scratch now.
