### ISSUE TITLE
pygame.error: mixer not initialized

### ISSUE THREAD

**Issue by NetSpida** [adangert/JoustMania#305]
During startup I get the following error:
```
Traceback (most recent call last):
  File "/home/joustmania/JoustMania/piparty.py", line 1053, in <module>
    InitAudio()
  File "/home/joustmania/JoustMania/piparty.py", line 630, in game_loop
    self.check_game_trigger()
  File "/home/joustmania/JoustMania/piparty.py", line 876, in check_start_game
    self.random_added.append(serial)
  File "/home/joustmania/JoustMania/piaudio.py", line 192, in __init__
    self.sample_ = pygame.mixer.Sound(file=fname)
pygame.error: mixer not initialized
```

**Comment by NetSpida** [comment]
Possibly the issue might be caused by my solution to https://github.com/adangert/JoustMania/issues/301

**Comment by adangert** [comment]
Fixed for the pi 4 on both bookworm and bullseye from #301
