### ISSUE TITLE
Pairing a controller crashes game

### ISSUE THREAD

**Issue by swartzd** [adangert/JoustMania#343]
Fresh Raspbian (64bit) install + fresh clone of the repo
Plug in a controller, it appears to pair (white light) and then the game crashes.

`PSMOVE WARNING] No calibration file found (/etc/psmoveapi/00_06_f5_15_a6_30.calibration or /etc/psmoveapi/00_06_f5_15_a6_30.calibration)
[PSMOVE WARNING] Magnetometer in 00:06:f5:15:a6:30 not yet calibrated.
[PAIRING LINUX] Running: 'systemctl stop bluetooth.service'
Job for bluetooth.service canceled.
[PAIRING LINUX] Automatic stop of bluetooth.service failed.
[PAIRING LINUX] Writing file: /var/lib/bluetooth/00:15:83:E7:A8:96/00:06:F5:15:A6:30/info
[PAIRING LINUX] Writing file: /var/lib/bluetooth/00:15:83:E7:A8:96/cache/00:06:F5:15:A6:30
[PAIRING LINUX] Running: 'systemctl start bluetooth.service'
Traceback (most recent call last):
  File "/home/joust/JoustMania/piparty.py", line 1224, in <module>
    piparty.game_loop()
  File "/home/joust/JoustMania/piparty.py", line 700, in game_loop
    self.check_for_new_moves()
  File "/home/joust/JoustMania/piparty.py", line 384, in check_for_new_moves
    self.enable_bt_scanning(True)
  File "/home/joust/JoustMania/piparty.py", line 401, in enable_bt_scanning
    if jm_dbus.enable_adapter(hci):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joust/JoustMania/jm_dbus.py", line 116, in enable_adapter
    raise e
  File "/home/joust/JoustMania/jm_dbus.py", line 108, in enable_adapter
    iface.Set('org.bluez.Adapter1', 'Powered', True)
  File "/home/joust/JoustMania/venv/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joust/JoustMania/venv/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.bluez.Error.Busy:

Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joust/JoustMania/piaudio.py", line 121, in audio_loop
    elif(fname['song'] != ''):
         ~~~~~^^^^^^^^
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.11/multiprocessing/managers.py", line 821, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by swartzd** [comment]
this is what the bluetooth service is doing
procedure: started log follow, plugged controller in via usb and recorded the output until the game crashed.

 sudo journalctl -b 0 -u bluetooth -f
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:40:13 joust bluetoothd[705]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex



Nov 02 17:41:45 joust systemd[1]: Stopping bluetooth.service - Bluetooth service...
Nov 02 17:41:45 joust bluetoothd[705]: Terminating
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Endpoint unregistered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[705]: Stopping SDP server
Nov 02 17:41:45 joust bluetoothd[705]: Exit
Nov 02 17:41:45 joust systemd[1]: bluetooth.service: Deactivated successfully.
Nov 02 17:41:45 joust systemd[1]: Stopped bluetooth.service - Bluetooth service.
Nov 02 17:41:45 joust systemd[1]: bluetooth.service: Consumed 6.861s CPU time.
Nov 02 17:41:45 joust systemd[1]: Starting bluetooth.service - Bluetooth service...
Nov 02 17:41:45 joust (uetoothd)[2075]: ConfigurationDirectory 'bluetooth' already exists but the mode is different. (File system: 755 ConfigurationDirectoryMode: 555)
Nov 02 17:41:45 joust bluetoothd[2075]: Bluetooth daemon 5.66
Nov 02 17:41:45 joust systemd[1]: Started bluetooth.service - Bluetooth service.
Nov 02 17:41:45 joust bluetoothd[2075]: Starting SDP server
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/audio/vcp.c:vcp_init() D-Bus experimental not enabled
Nov 02 17:41:45 joust bluetoothd[2075]: src/plugin.c:plugin_init() Failed to init vcp plugin
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/audio/mcp.c:mcp_init() D-Bus experimental not enabled
Nov 02 17:41:45 joust bluetoothd[2075]: src/plugin.c:plugin_init() Failed to init mcp plugin
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/audio/bap.c:bap_init() D-Bus experimental not enabled
Nov 02 17:41:45 joust bluetoothd[2075]: src/plugin.c:plugin_init() Failed to init bap plugin
Nov 02 17:41:45 joust bluetoothd[2075]: Bluetooth management interface 1.22 initialized
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Nov 02 17:41:45 joust bluetoothd[2075]: sap-server: Operation not permitted (1)
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Nov 02 17:41:45 joust bluetoothd[2075]: sap-server: Operation not permitted (1)
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Nov 02 17:41:45 joust bluetoothd[2075]: sap-server: Operation not permitted (1)
Nov 02 17:41:45 joust bluetoothd[2075]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Nov 02 17:41:45 joust bluetoothd[2075]: sap-server: Operation not permitted (1)
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/ldac
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_hd
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_g
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/sbc
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/faststream_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Nov 02 17:41:45 joust bluetoothd[2075]: Endpoint registered: sender=:1.25 path=/MediaEndpoint/A2DPSource/opus_05_duplex

**Comment by swartzd** [comment]
after rebooting the Pi, the controllers are indeed paired and can play the game (but it is a painful process to pair controllers if  you have to restart the pi every time :D

**Comment by swartzd** [comment]
along with that, discovered that some game modes (such as zombies) launched fine with small amounts of controllers and crashed when we had 11 or so (did not do extensive testing to figure out at what quantity things had problems)
