### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Robotopera** [adangert/JoustMania#69]
Manually starting gives the following error:

`Traceback (most recent call last):
  File "/home/pi/JoustMania/piparty.py", line 2, in <module>
    import psmove
  File "/home/pi/psmoveapi/build/psmove.py", line 28, in <module>
    _psmove = swig_import_helper()
  File "/home/pi/psmoveapi/build/psmove.py", line 24, in swig_import_helper
    _mod = imp.load_module('_psmove', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dynamic module does not define init function (PyInit__psmove)
`

**Comment by Robotopera** [comment]
Purging all versions of python and manually reinstalling python 3 fixed the issue. Any instances of python in the setup script were replaced with python3.
